apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: miniflux
  name: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: miniflux
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: miniflux
    spec:
      containers:
      - env:
        - name: ADMIN_PASSWORD
          value: xxxxx
        - name: ADMIN_USERNAME
          value: admin
        - name: BASE_URL
          value: https://rss.xxxxx.com/
        - name: CREATE_ADMIN
          value: "1"
        - name: DATABASE_URL
          value: postgres://miniflux:12345abc@db/miniflux?sslmode=disable
        - name: PGID
          value: "1000"
        - name: POLLING_PARSING_ERROR_LIMIT
          value: "2"
        - name: PUID
          value: "1000"
        - name: RUN_MIGRATIONS
          value: "1"
        image: miniflux/miniflux:latest
        name: miniflux
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
