apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
  - name: mp
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
  type: ClusterIP  
