apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rsshub
  name: rsshub
spec:
  ports:
  - name: hmp
    port: 1200
    targetPort: 1200
  selector:
    io.kompose.service: rsshub
  type: ClusterIP
