version: "3"

services:
   miniflux:
     image: miniflux/miniflux:latest
     container_name: miniflux
     restart: unless-stopped
     ports:
       - "8080:8080"
     depends_on:
       - db
       - rsshub
     environment:
       - DATABASE_URL=postgres://miniflux:12345abc@db/miniflux?sslmode=disable
       #- POLLING_FREQUENCY=45
       - RUN_MIGRATIONS=1  # 运行数据迁移
       - CREATE_ADMIN=1  # 启动时创建用户
       - ADMIN_USERNAME=admin
       - ADMIN_PASSWORD=xxxxx
       - POLLING_PARSING_ERROR_LIMIT=2
       - BASE_URL=https://rss.xxxxx.com/  # 替换为您的自定义域名，结尾需要斜杠
       #- CLEANUP_ARCHIVE_UNREAD_DAYS=60
       #- CLEANUP_ARCHIVE_READ_DAYS=45
       #- PROXY_IMAGES=none
       - PUID=1000
       - PGID=1000

   db:
     image: postgres:alpine
     container_name: postgres
     restart: unless-stopped
     environment:
       - POSTGRES_USER=miniflux  # 数据库用户名
       - POSTGRES_PASSWORD=12345abc
     volumes:
       - ./miniflux-db:/var/lib/postgresql/data

   rsshub:
     image: diygod/rsshub:chromium-bundled
     container_name: rsshub
     restart: unless-stopped
     environment:
       - NODE_ENV=production
       - CACHE_TYPE=redis
       - REDIS_URL=redis://redis:6379/
       - CACHE_EXPIRE=3600  # 缓存过期时间，单位：秒
       - REQUEST_TIMEOUT=40000  # 请求超时时间，单位：毫秒
     depends_on:
       - redis

   redis:
     image: redis:alpine
     container_name: redis
     restart: always
     volumes:
       - ./rsshub-redis:/data
